/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License"){return 0;}
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_MEDIA_BUSINESS_CODE_H
#define OHOS_MEDIA_BUSINESS_CODE_H

namespace OHOS::Media {

enum class MediaLibraryBusinessCode : uint32_t {
    MEDIA_BUSINESS_CODE_START = 0,
    REMOVE_FORM_INFO = 3,
    REMOVE_GALLERY_FORM_INFO,
    SAVE_FORM_INFO,
    SAVE_GALLERY_FORM_INFO,
    UPDATE_GALLERY_FORM_INFO,
    SUBMIT_CLOUD_ENHANCEMENT_TASKS,
    PRIORITIZE_CLOUD_ENHANCEMENT_TASK,
    CANCEL_CLOUD_ENHANCEMENT_TASKS,
    CANCEL_ALL_CLOUD_ENHANCEMENT_TASKS,
    PAH_OPEN,
    PAH_START_THUMBNAIL_CREATION_TASK,
    PAH_STOP_THUMBNAIL_CREATION_TASK,
    ASSETS_BUSINESS_CODE_START = 10000,
    CLONE_ASSET,
    REVERT_TO_ORIGINAL,
    COMMIT_EDITED_ASSET,
    PAH_PUBLIC_CREATE_ASSET,
    PAH_SYSTEM_CREATE_ASSET,
    PAH_PUBLIC_CREATE_ASSET_FOR_APP,
    PAH_SYSTEM_CREATE_ASSET_FOR_APP,
    PAH_SYSTEM_CREATE_ASSET_FOR_APP_WITH_MODE,
    PAH_SYSTEM_CREATE_ASSET_FOR_APP_WITH_ALBUM,
    PAH_PUBLIC_SET_TITLE,
    PAH_SYSTEM_SET_PENDING,
    PAH_SYSTEM_SET_FAVORITE,
    PAH_SYSTEM_SET_USER_COMMENT,
    PAH_SYSTEM_BATCH_SET_HIDDEN,
    PAH_SYSTEM_BATCH_SET_FAVORITE,
    PAH_SYSTEM_BATCH_SET_RECENT_SHOW,
    PAH_SYSTEM_BATCH_SET_USER_COMMENT,
    PAH_SYS_TRASH_PHOTOS,
    PAH_TRASH_PHOTOS,
    PAH_DELETE_PHOTOS,
    DELETE_PHOTOS_COMPLETED,
    START_DOWNLOAD_CLOUDMEDIA,
    PAUSE_DOWNLOAD_CLOUDMEDIA,
    CANCEL_DOWNLOAD_CLOUDMEDIA,
    RETAIN_CLOUDMEDIA_ASSET,
    PAH_GRANT_PHOTO_URI_PERMISSION,
    PAH_GRANT_PHOTO_URIS_PERMISSION,
    PAH_CANCEL_PHOTO_URI_PERMISSION,
    ASSET_CHANGE_SET_FAVORITE,
    ASSET_CHANGE_SET_HIDDEN,
    ASSET_CHANGE_SET_USER_COMMENT,
    ASSET_CHANGE_SET_LOCATION,
    ASSET_CHANGE_SET_TITLE,
    ASSET_CHANGE_SET_EDIT_DATA,
    ASSET_CHANGE_SUBMIT_CACHE,
    ASSET_CHANGE_CREATE_ASSET,
    ASSET_CHANGE_ADD_IMAGE,
    SET_CAMERA_SHOT_KEY,
    SAVE_CAMERA_PHOTO,
    DISCARD_CAMERA_PHOTO,
    SET_EFFECT_MODE,
    SET_ORIENTATION,
    SET_VIDEO_ENHANCEMENT_ATTR,
    SET_SUPPORTED_WATERMARK_TYPE,
    ALBUMS_BUSINESS_CODE_START = 20000,
    DELETE_HIGH_LIGHT_ALBUMS,
    PAH_SYSTEM_CREATE_ALBUM,
    PAH_DELETE_PHOTO_ALBUMS,
    CHANGE_REQUEST_SET_ALBUM_NAME,
    CHANGE_REQUEST_SET_COVER_URI,
    CHANGE_REQUEST_SET_IS_ME,
    CHANGE_REQUEST_SET_DISPLAY_LEVEL,
    CHANGE_REQUEST_DISMISS,
    SET_HIGH_LIGHT_USER_ACTION_DATA,
    SET_SUBTITLE,
    CHANGE_REQUEST_ADD_ASSETS,
    CHANGE_REQUEST_REMOVE_ASSETS,
    CHANGE_REQUEST_MOVE_ASSETS,
    CHANGE_REQUEST_RECOVER_ASSETS,
    CHANGE_REQUEST_DELETE_ASSETS,
    CHANGE_REQUEST_DISMISS_ASSETS,
    CHANGE_REQUEST_MERGE_ALBUM,
    CHANGE_REQUEST_PLACE_BEFORE,
    CHANGE_REQUEST_SET_ORDER_POSITION,
    PAH_COMMIT_MODIFY,
    PAH_ADD_ASSETS,
    PAH_REMOVE_ASSETS,
    PAH_RECOVER_ASSETS,
    PAH_SET_COVER_URI,
    MEDIA_CLOUD_CODE_START = 30000,
    MEDIA_CLOUD_CODE_END = 39999,
    MEDIA_REFRESH_CODE_START = 40000,
    NOTIFY_FOR_RECHECK,
    MEDIA_REFRESH_CODE_END = 49999,
};
}  // namespace OHOS::Media
#endif  // OHOS_MEDIA_BUSINESS_CODE_H