/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef NOTIFYCHANGE_FUZZER_H
#define NOTIFYCHANGE_FUZZER_H

#define FUZZ_PROJECT_NAME "medialibraryrefreshmanager"

#include "userfilemgr_uri.h"
#include "album_operation_uri.h"
#include "data_secondary_directory_uri.h"
#include "cloud_enhancement_uri.h"
#include "mediatool_uri.h"

#include <string>
#include <vector>

namespace OHOS {
namespace Media {
const std::vector<std::string> EXTENSION_FUZZER_URI_LISTS = {
    // API9 compat photo operations constants
    CONST_URI_CREATE_PHOTO,
    CONST_URI_CLOSE_PHOTO,
    CONST_URI_UPDATE_PHOTO,
    CONST_URI_QUERY_PHOTO,

    // API9 compat audio operations constants
    CONST_URI_QUERY_AUDIO,
    CONST_URI_CLOSE_AUDIO,
    CONST_URI_UPDATE_AUDIO,
    CONST_URI_CREATE_AUDIO,
    CONST_URI_CLOSE_FILE,
    CONST_URI_UPDATE_FILE,
    CONST_URI_CREATE_FILE,

    // Photo album operations constants
    CONST_URI_QUERY_PHOTO_ALBUM,
    CONST_URI_DELETE_PHOTOS,
    CONST_URI_COMPAT_DELETE_PHOTOS,

    // Photo map operations constants
    CONST_URI_QUERY_PHOTO_MAP,

    // Scanner tool operation constants
    CONST_URI_SCANNER,

    // Mediatool delete operation constants
    CONST_URI_DELETE_TOOL,

    // UserFileManager photo operation constants
    CONST_UFM_CREATE_PHOTO,
    CONST_UFM_CREATE_PHOTO_COMPONENT,
    CONST_UFM_CLOSE_PHOTO,
    CONST_UFM_UPDATE_PHOTO,
    CONST_UFM_QUERY_PHOTO,
    CONST_UFM_SET_USER_COMMENT,
    CONST_UFM_GET_INDEX,
    CONST_UFM_HIDE_PHOTO,

    // UserFileManager audio operation constants
    CONST_UFM_CREATE_AUDIO,
    CONST_UFM_CREATE_AUDIO_COMPONENT,
    CONST_UFM_CLOSE_AUDIO,
    CONST_UFM_QUERY_AUDIO,
    CONST_UFM_UPDATE_AUDIO,
    CONST_URI_DELETE_AUDIO,

    // UserFileManager album operation constants
    CONST_UFM_CREATE_PHOTO_ALBUM,
    CONST_UFM_DELETE_PHOTO_ALBUM,
    CONST_UFM_UPDATE_PHOTO_ALBUM,
    CONST_UFM_QUERY_PHOTO_ALBUM,
    CONST_UFM_QUERY_HIDDEN_ALBUM,
    CONST_UFM_PHOTO_ALBUM_ADD_ASSET,
    CONST_UFM_PHOTO_ALBUM_REMOVE_ASSET,
    CONST_UFM_QUERY_PHOTO_MAP,
    CONST_UFM_RECOVER_PHOTOS,
    CONST_UFM_DELETE_PHOTOS,

    // PhotoAccessHelper photo operation constants
    CONST_PAH_CREATE_PHOTO,
    CONST_PAH_CREATE_PHOTO_COMPONENT,
    CONST_PAH_CLOSE_PHOTO,
    CONST_PAH_UPDATE_PHOTO,
    CONST_PAH_UPDATE_PHOTO_COMPONENT,
    CONST_PAH_TRASH_PHOTO,
    CONST_PAH_QUERY_PHOTO,
    CONST_PAH_EDIT_USER_COMMENT_PHOTO,
    CONST_PAH_HIDE_PHOTOS,
    CONST_PAH_SUBMIT_CACHE,
    CONST_PAH_ADD_FILTERS,
    CONST_PAH_BATCH_UPDATE_FAVORITE,
    CONST_PAH_BATCH_UPDATE_USER_COMMENT,
    CONST_PAH_BATCH_UPDATE_OWNER_ALBUM_ID,
    CONST_PAH_GET_ANALYSIS_INDEX,
    CONST_PAH_DISCARD_CAMERA_PHOTO,
    CONST_PAH_SAVE_CAMERA_PHOTO,
    CONST_PAH_SCAN_WITHOUT_ALBUM_UPDATE,
    CONST_PATH_SAVE_PICTURE,

    // MultiStages capture related operation uri
    CONST_PAH_SET_PHOTO_QUALITY,
    CONST_PAH_PROCESS_IMAGE,
    CONST_PAH_ADD_IMAGE,
    CONST_PAH_SET_LOCATION,
    CONST_PAH_CANCEL_PROCESS_IMAGE,
    CONST_PAH_REMOVE_MSC_TASK,

    // Generate thumbnails in batches operation uri
    CONST_PAH_START_GENERATE_THUMBNAILS,
    CONST_PAH_STOP_GENERATE_THUMBNAILS,
    CONST_PAH_ADD_LOWQUALITY_IMAGE,

    // PhotoAccessHelper album operation constants
    CONST_PAH_CREATE_PHOTO_ALBUM,
    CONST_PAH_DELETE_PHOTO_ALBUM,
    CONST_PAH_UPDATE_PHOTO_ALBUM,
    CONST_PAH_SET_PHOTO_ALBUM_NAME,
    CONST_PAH_QUERY_PHOTO_ALBUM,
    CONST_PAH_QUERY_HIDDEN_ALBUM,
    CONST_PAH_PHOTO_ALBUM_ADD_ASSET,
    CONST_PAH_PHOTO_ALBUM_REMOVE_ASSET,
    CONST_PAH_QUERY_PHOTO_MAP,
    CONST_PAH_RECOVER_PHOTOS,
    CONST_PAH_DELETE_PHOTOS,
    CONST_PAH_ORDER_ALBUM,
    CONST_PAH_COMMIT_EDIT_PHOTOS,
    CONST_PAH_REVERT_EDIT_PHOTOS,
    CONST_PAH_PORTRAIT_DISPLAY_LEVLE,
    CONST_PAH_PORTRAIT_IS_ME,
    CONST_PAH_PORTRAIT_ANAALBUM_ALBUM_NAME,
    CONST_PAH_PORTRAIT_MERGE_ALBUM,
    CONST_PAH_DISMISS_ASSET,
    CONST_PAH_PORTRAIT_ANAALBUM_COVER_URI,
    CONST_PAH_GROUP_ANAALBUM_DISMISS,
    CONST_PAH_GROUP_ANAALBUM_ALBUM_NAME,
    CONST_PAH_GROUP_ANAALBUM_COVER_URI,
    CONST_PAH_HIGHLIGHT_COVER_URI,
    CONST_PAH_HIGHLIGHT_ALBUM_NAME,

    CONST_PAH_QUERY_ANA_PHOTO_ALBUM,
    CONST_PAH_QUERY_ANA_PHOTO_MAP,
    CONST_PAH_INSERT_ANA_PHOTO_ALBUM,
    CONST_PAH_UPDATE_ANA_PHOTO_ALBUM,
    CONST_PAH_INSERT_ANA_PHOTO_MAP,

    CONST_PAH_QUERY_ANA_OCR,
    CONST_PAH_QUERY_ANA_ATTS,
    CONST_PAH_QUERY_ANA_LABEL,
    CONST_PAH_QUERY_ANA_VIDEO_LABEL,
    CONST_PAH_QUERY_ANA_FACE,
    CONST_PAH_QUERY_ANA_FACE_TAG,
    CONST_PAH_QUERY_ANA_OBJECT,
    CONST_PAH_QUERY_ANA_RECOMMENDATION,
    CONST_PAH_QUERY_ANA_SEGMENTATION,
    CONST_PAH_QUERY_ANA_COMPOSITION,
    CONST_PAH_QUERY_ANA_HEAD,
    CONST_PAH_QUERY_ANA_POSE,
    CONST_PAH_STORE_FORM_MAP,
    CONST_PAH_REMOVE_FORM_MAP,
    CONST_PAH_QUERY_ANA_SAL,
    CONST_PAH_QUERY_ANA_ADDRESS,
    CONST_PAH_QUERY_GEO_PHOTOS,
    CONST_PAH_QUERY_HIGHLIGHT_COVER,
    CONST_PAH_QUERY_HIGHLIGHT_PLAY,
    CONST_PAH_QUERY_ANA_TOTAL,
    CONST_PAH_QUERY_MULTI_CROP,
    CONST_PAH_UPDATE_ANA_FACE,

    // PhotoAccessHelper moving photo
    CONST_PAH_MOVING_PHOTO_SCAN,

    // PhotoAccessHelper cloud enhancement
    CONST_PAH_CLOUD_ENHANCEMENT_ADD,
    CONST_PAH_CLOUD_ENHANCEMENT_PRIORITIZE,
    CONST_PAH_CLOUD_ENHANCEMENT_CANCEL,
    CONST_PAH_CLOUD_ENHANCEMENT_CANCEL_ALL,
    CONST_PAH_CLOUD_ENHANCEMENT_SYNC,
    CONST_PAH_CLOUD_ENHANCEMENT_QUERY,
    CONST_PAH_CLOUD_ENHANCEMENT_GET_PAIR,

    // mediatool operation constants
    CONST_TOOL_CREATE_PHOTO,
    CONST_TOOL_CREATE_AUDIO,
    CONST_TOOL_CLOSE_PHOTO,
    CONST_TOOL_CLOSE_AUDIO,
    CONST_TOOL_QUERY_PHOTO,
    CONST_TOOL_QUERY_AUDIO,
    CONST_TOOL_LIST_PHOTO,
    CONST_TOOL_LIST_AUDIO,
    CONST_TOOL_UPDATE_PHOTO,
    CONST_TOOL_UPDATE_AUDIO,
    CONST_TOOL_DELETE_PHOTO,
    CONST_TOOL_DELETE_AUDIO,

    // Miscellaneous operation constants
    CONST_LOG_MOVING_PHOTO,
    CONST_PAH_FINISH_REQUEST_PICTURE,

    CONST_MEDIALIBRARY_DIRECTORY_URI,
    CONST_MEDIALIBRARY_BUNDLEPERM_URI,

    CONST_MEDIALIBRARY_CHECK_URIPERM_URI,
    CONST_MEDIALIBRARY_GRANT_URIPERM_URI,

    CONST_MEDIALIBRARY_AUDIO_URI,
    CONST_MEDIALIBRARY_VIDEO_URI,
    CONST_MEDIALIBRARY_IMAGE_URI,
    CONST_MEDIALIBRARY_FILE_URI,
    CONST_MEDIALIBRARY_ALBUM_URI,
    CONST_MEDIALIBRARY_SMARTALBUM_CHANGE_URI,
    CONST_MEDIALIBRARY_DEVICE_URI,
    CONST_MEDIALIBRARY_SMART_URI,
    CONST_MEDIALIBRARY_REMOTEFILE_URI,
};
} // namespace Media
} // namespace OHOS

#endif