/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_ALBUM_GRET_LIST_H
#define OHOS_ALBUM_GRET_LIST_H

#include <string>
#include <unordered_set>

namespace OHOS::Media {
namespace AlbumGreyList {

const std::unordered_set<std::string> LAKE_ALBUM_LIST = {
    "/mmcache",
    "/AnyofficeiconDownload",
    "/com.inveno.hwread/Interset",
    "/com.taobao.ju.android/splash",
    "/ShareSDK/com.sdu.didi.psnger/cache/images",
    "/soufun/res/cache/splash_ads",
    "/ShareSDK/com.sinovatech.unicom.ui/cache/image",
    "/BaiduMap/cache",
    "/sogou/sga/dimcode",
    "/AnyOffice/adv",
    "/carowner/h5cache",
    "/DidiScreenAd",
    "/mwqi/cache",
    "/Mob/com.sdu.didi.psnger/cache/images",
    "/xingjiabi/live/Drive",
    "/UCDownloads/picview_tmp",
    "/lianjia/lj_social_cache",
    "/tuhu/hwad",
    "/tuhu/ad",
    "/SignalSiteMap/indoorTest",
    "/tencent/tassistant/photon",
    "/tencent/tassistant/file",
    "/com.chenghuitong/picture/cache",
    "/ktv/pic",
    "/mwqi/cache",
    "/DidiScreenAd",
    "/Download/ads",
    "/qqmusic/dts/assets/images",
    "/qqmusic/dts_auto/assets/images",
    "/HwRemoteController/temp/Cache",
    "/Gome/HomeBottomSkin",
    "/Download/Screenshot/tmp",
    "/183/LizhiFM/Caches",
    "/360/MobileSafe/temp",
    "/360Video/temp",
    "/360yun/cache",
    "/51zhangdan/tabBackgroundPic",
    "/BaiduNavi/cache/ImageCache",
    "/baofeng/download/middle_ad",
    "/com.ushaqi.zhuishush/cache",
    "/CTRIP/cache",
    "/CTRIP/avatar",
    "/DuoDuoHouse/cache/img",
    "/eastmoneyjj/news",
    "/hers/cache",
    "/iCredit/tempcapture",
    "/iFlyME/imagecache",
    "/immomo/cache",
    "/immomo/avatar",
    "/Ingkee/newImage/tag",
    "/ishowdubing_justalk/video",
    "/ishowdubing_justalk/msg/pic",
    "/jumei/jmframe/cache/pics",
    "/jumei/JMH5Container",
    "/keep/ads",
    "/kuaidi100/logoCache",
    "/kugou/ktv/ktv_notification",
    "/lufax/cache",
    "/netease/cloudmusic/Cache/ImageCache",
    "/netease/cloudmusic/Cache/Image",
    "/powerword/cache",
    "/qqmusic/splash",
    "/qqpim/softicon",
    "/qqpim/splash",
    "/SMZDM/cache",
    "/SogouExplorer/download/bootstrapAD",
    "/tencent/QQmail/imagecache",
    "/TianQiTong/cache",
    "/TongCheng/avatar",
    "/tuniu/avatar",
    "/UMETrip/images/head",
    "/wochachaCache",
    "/xiangha/cache",
    "/xiangha/long",
    "/Yixin/img_cache",
    "/Yixin/avatar",
    "/yuntutv/ad",
    "/yymobile/config",
    "/Huawei/HuaweiIT",
    "/HRAndroidFrame",
    "/HuaweiSystem",
    "/Huawei/Sns",
    "/log/hiview/onekeycapture",
    "/tencent/tassistant/skin_pkg",
    "/meishij/Temp",
    "/NaviOne.CM/NaviParamsFile",
    "/人民日报/imgCache",
    "/imageCache",
    "/qk/icons",
    "/JDB/cache",
    "/huluxia/tool",
    "/tencent/tassistant/gif",
    "/tencent/tassistant/pic",
    "/FeiNiu/cache",
    "/时光网/tem_pic",
    "/xiaokaxiu/image_cache",
    "/liepin/cache",
    "/4399Game/videoCache",
    "/moxiu/temp",
    "/mierjunshi/imgCache",
    "/sina/SinaSports/cache",
    "/XiaoJi/Cache/Icon",
    "/DuoKan/Cache",
    "/SNEPA/cache/images",
    "/ZOL/userinfo",
    "/CloudSEE/head",
    "/CloudSEE/welcome",
    "/zongheng/cache",
    "/zongheng/tempImage",
    "/sogou/firstscreen",
    "/sub/kekeyiyu/Caches/Image",
    "/baixing/header",
    "/baixing/icon",
    "/sdjj/tmp",
    "/jymao/frescoimg_small",
    "/pris/cache",
    "/2345Browser/Cache",
    "/XMEye/temp_images",
    "/font/backup",
    "/liulianglaile/file",
    "/MobileKTV/Buffer",
    "/MomentCam/heads",
    "/MomentCam/multy",
    "/guazi_theme_image",
    "/iaround/cacheimage_new",
    "/u17phone/cache",
    "/enavi/Dynamic",
    "/violationquery/image_catch",
    "/pcauto/cache",
    "/pcauto/userAvatar",
    "/TiantianGame/cachePic",
    "/V_WeChat/Emoji",
    "/WhatsLIVE/Cache",
    "/VisitActivity/cache",
    "/kkcredit/rn",
    "/doupai/pictures/temp1",
    "/lolBoxCache",
    "/ojc/cache",
    "/MFAd",
    "/FingerCache",
    "/driverhelper/cache/headImage",
    "/lianjia/lj_social_cache",
    "/MissFresh/cache",
    "/jtjr/jiaoyoubao/data/cache",
    "/gtgj_bitmapcache",
    "/boc/temp",
    "/autohomemain/ar/armode",
    "/Mob/com.xcar.activity",
    "/money_shield/splash_image",
    "/Changker/imageCache",
    "/dragonpass/html/orderDetail",
    "/qyer/qyerguide",
    "/youkuvr/Cache",
    "/OGQ/TEDAIR/Cache",
    "/Changker/imageCache/head_img",
    "/baidu/hybird/com.baidu.netdisk/icons",
    "/baidu/hybird/noti_icons",
    "/tencent/MicroMsg/wallet/luckyMoneyEffect/1/package",
    "/aloha/1ac6f0ea25a2507e9550cc441da8c7e6",
    "/tencent/zebra",
    "/autohomemain/ar/picture",
    "/iyuba/concept2/audio/sound",
    "/NJCBSPL/MoblieBank",
    "/th",
    "/iyuba/concept2/ad",
    "/me.yidui/assets",
    "/sina/weibo/storage/biz_common/lighttheme",
    "/sogou/voice/notify/resource",
    "/freshfresh",
};
} // namespace AlbumGreyList
} // namespace OHOS_Media
#endif // OHOS_ALBUM_GRET_LIST_H