/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef NOTIFYCHANGE_FUZZER_H
#define NOTIFYCHANGE_FUZZER_H

#define FUZZ_PROJECT_NAME "medialibrary_mtp_fuzzer"

#include <vector>
#include "mtp_constants.h"

namespace OHOS {
namespace Media {
const std::vector<uint16_t> MTP_OPERATIONS_LIST = {
    MTP_OPERATION_GET_DEVICE_INFO_CODE,
    MTP_OPERATION_OPEN_SESSION_CODE,
    MTP_OPERATION_CLOSE_SESSION_CODE,
    MTP_OPERATION_GET_STORAGE_IDS_CODE,
    MTP_OPERATION_GET_STORAGE_INFO_CODE,
    MTP_OPERATION_GET_NUM_OBJECTS_CODE,
    MTP_OPERATION_GET_OBJECT_HANDLES_CODE,
    MTP_OPERATION_GET_OBJECT_INFO_CODE,
    MTP_OPERATION_GET_OBJECT_CODE,
    MTP_OPERATION_GET_THUMB_CODE,
    MTP_OPERATION_DELETE_OBJECT_CODE,
    MTP_OPERATION_SEND_OBJECT_INFO_CODE,
    MTP_OPERATION_SEND_OBJECT_CODE,
    MTP_OPERATION_INITIATE_CAPTURE_CODE,
    MTP_OPERATION_RESET_DEVICE_CODE,
    MTP_OPERATION_SELF_TEST_CODE,
    MTP_OPERATION_SET_OBJECT_PROTECTION_CODE,
    MTP_OPERATION_POWER_DOWN_CODE,
    MTP_OPERATION_GET_DEVICE_PROP_DESC_CODE,
    MTP_OPERATION_GET_DEVICE_PROP_VALUE_CODE,
    MTP_OPERATION_SET_DEVICE_PROP_VALUE_CODE,
    MTP_OPERATION_RESET_DEVICE_PROP_VALUE_CODE,
    MTP_OPERATION_TERMINATE_OPEN_CAPTURE_CODE,
    MTP_OPERATION_MOVE_OBJECT_CODE,
    MTP_OPERATION_COPY_OBJECT_CODE,
    MTP_OPERATION_GET_PARTIAL_OBJECT_CODE,
    MTP_OPERATION_INITIATE_OPEN_CAPTURE_CODE,
    MTP_OPERATION_GET_OBJECT_PROPS_SUPPORTED_CODE,
    MTP_OPERATION_GET_OBJECT_PROP_DESC_CODE,
    MTP_OPERATION_GET_OBJECT_PROP_VALUE_CODE,
    MTP_OPERATION_SET_OBJECT_PROP_VALUE_CODE,
    MTP_OPERATION_GET_OBJECT_PROP_LIST_CODE,
    MTP_OPERATION_SET_OBJECT_PROP_LIST_CODE,
    MTP_OPERATION_GET_INTERDEPENDENT_PROPDESC_CODE,
    MTP_OPERATION_SEND_OBJECT_PROP_LIST_CODE,
    MTP_OPERATION_GET_OBJECT_REFERENCES_CODE,
    MTP_OPERATION_SET_OBJECT_REFERENCES_CODE,
    MTP_OPERATION_SKIP_CODE,
};
} // namespace Media
} // namespace OHOS
#endif